### ISSUE TITLE
evdi won't compile on bullseys's new 5.9 kernel

### ISSUE THREAD

**Issue by tobias-weiss** [AdnanHodzic/displaylink-debian#480]
I have to stick to 5.8 kernel, there the module does work.

root@kaczmarski:/home/tobias/Downloads/displaylink-debian# ./evdi.sh 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libelf-dev is already the newest version (0.181-1).
libdrm-dev is already the newest version (2.4.102-1).
The following packages were automatically installed and are no longer required:
  libbrlapi0.7 liborcus-0.15-0 liborcus-parser-0.15-0 libpgm-5.2-0 linux-image-5.8.0-2-amd64
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
find: paths must precede expression: `displaylink-installer.patch'
find: possible unquoted pattern after predicate `-name'?
https://crazy.dev.frugalware.org/evdi-all-in-one-fixes.patch
--2020-10-27 16:26:27--  https://crazy.dev.frugalware.org/evdi-all-in-one-fixes.patch
Resolving crazy.dev.frugalware.org (crazy.dev.frugalware.org)... 85.10.194.195
Connecting to crazy.dev.frugalware.org (crazy.dev.frugalware.org)|85.10.194.195|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File 'evdi-all-in-one-fixes.patch' not modified on server. Omitting download.

Cloning into 'evdi'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 46 (delta 2), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (46/46), 66.98 KiB | 623.00 KiB/s, done.
Note: switching to 'dc595db636845aef39490496bc075f6bf067106c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

patching file .travis.yml
Hunk #1 FAILED at 26.
1 out of 1 hunk FAILED -- saving rejects to file .travis.yml.rej
patching file Makefile
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file Makefile.rej
patching file library/Makefile
Hunk #1 FAILED at 2.
1 out of 1 hunk FAILED -- saving rejects to file library/Makefile.rej
patching file module/Makefile
Hunk #1 FAILED at 43.
1 out of 1 hunk FAILED -- saving rejects to file module/Makefile.rej
patching file module/evdi_drv.c
Hunk #1 FAILED at 81.
1 out of 1 hunk FAILED -- saving rejects to file module/evdi_drv.c.rej
patching file module/evdi_drv.h
Hunk #1 FAILED at 20.
Hunk #2 FAILED at 51.
Hunk #3 FAILED at 112.
3 out of 3 hunks FAILED -- saving rejects to file module/evdi_drv.h.rej
patching file module/evdi_gem.c
Hunk #1 FAILED at 61.
Hunk #2 FAILED at 254.
Hunk #3 FAILED at 569.
Hunk #4 FAILED at 581.
4 out of 4 hunks FAILED -- saving rejects to file module/evdi_gem.c.rej
CFLAGS="-Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers" make -C module 
make[1]: Entering directory '/home/tobias/Downloads/displaylink-debian/evdi/module'
make -C /lib/modules/5.9.0-1-amd64/build M=$PWD
make[2]: Entering directory '/usr/src/linux-headers-5.9.0-1-amd64'
  AR      /home/tobias/Downloads/displaylink-debian/evdi/module/built-in.a
  CC [M]  /home/tobias/Downloads/displaylink-debian/evdi/module/evdi_drv.o
/home/tobias/Downloads/displaylink-debian/evdi/module/evdi_drv.c:92:3: error: 'struct drm_driver' has no member named 'gem_free_object'; did you mean 'gem_open_object'?
   92 |  .gem_free_object = evdi_gem_free_object,
      |   ^~~~~~~~~~~~~~~
      |   gem_open_object
/home/tobias/Downloads/displaylink-debian/evdi/module/evdi_drv.c:92:21: error: initialization of 'void (*)(struct drm_device *)' from incompatible pointer type 'void (*)(struct drm_gem_object *)' [-Werror=incompatible-pointer-types]
   92 |  .gem_free_object = evdi_gem_free_object,
      |                     ^~~~~~~~~~~~~~~~~~~~
/home/tobias/Downloads/displaylink-debian/evdi/module/evdi_drv.c:92:21: note: (near initialization for 'driver.lastclose')
/home/tobias/Downloads/displaylink-debian/evdi/module/evdi_drv.c: In function 'evdi_platform_probe':
/home/tobias/Downloads/displaylink-debian/evdi/module/evdi_drv.c:173:20: error: 'struct dev_archdata' has no member named 'iommu'
  173 |  pdev->dev.archdata.iommu = INTEL_IOMMU_DUMMY_DOMAIN;
      |                    ^
cc1: all warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-5.9.0-1-common/scripts/Makefile.build:288: /home/tobias/Downloads/displaylink-debian/evdi/module/evdi_drv.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.9.0-1-common/Makefile:1796: /home/tobias/Downloads/displaylink-debian/evdi/module] Error 2
make[2]: *** [/usr/src/linux-headers-5.9.0-1-common/Makefile:185: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-5.9.0-1-amd64'
make[1]: *** [Makefile:71: module] Error 2
make[1]: Leaving directory '/home/tobias/Downloads/displaylink-debian/evdi/module'
make: *** [Makefile:8: all] Error 2

**Comment by Barabazs** [comment]
evdi are still working on supporting 5.9

**Comment by mndz** [comment]
I'm getting the same error

**Comment by Barabazs** [comment]
@tobias-weiss @mndz support for 5.9 has been added.
pull the latest from master and give it a try.
